In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [88]:
df = pd.read_csv('data/clen_bike.csv')

In [89]:
df

      Unnamed: 0  owner            brand     price  kms_driven  age  power
0              0      1              TVS   35000.0     17654.0  3.0  110.0
1              1      1    Royal Enfield  119900.0     11000.0  4.0  350.0
2              2      1          Triumph  600000.0       110.0  8.0  675.0
3              3      1              TVS   65000.0     16329.0  4.0  180.0
4              4      1           Yamaha   80000.0     10000.0  3.0  150.0
...          ...    ...              ...       ...         ...  ...    ...
7301        9362      1             Hero   25000.0     48587.0  8.0  150.0
7302        9369      1            Bajaj   35000.0     60000.0  9.0  220.0
7303        9370      1  Harley-Davidson  450000.0      3430.0  4.0  750.0
7304        9371      1            Bajaj  139000.0     21300.0  4.0  400.0
7305        9372      1            Bajaj   80000.0      7127.0  5.0  220.0

[7306 rows x 7 columns]

In [90]:
df.drop('Unnamed: 0', axis= 1, inplace= True)

In [91]:
df

      owner            brand     price  kms_driven  age  power
0         1              TVS   35000.0     17654.0  3.0  110.0
1         1    Royal Enfield  119900.0     11000.0  4.0  350.0
2         1          Triumph  600000.0       110.0  8.0  675.0
3         1              TVS   65000.0     16329.0  4.0  180.0
4         1           Yamaha   80000.0     10000.0  3.0  150.0
...     ...              ...       ...         ...  ...    ...
7301      1             Hero   25000.0     48587.0  8.0  150.0
7302      1            Bajaj   35000.0     60000.0  9.0  220.0
7303      1  Harley-Davidson  450000.0      3430.0  4.0  750.0
7304      1            Bajaj  139000.0     21300.0  4.0  400.0
7305      1            Bajaj   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [92]:
df.duplicated().sum()

np.int64(0)

In [93]:
df.isnull().sum()

owner         0
brand         0
price         0
kms_driven    0
age           0
power         0
dtype: int64

In [94]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [95]:
brand_dic =  {
    'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
              }

df['brand']=df['brand'].map(brand_dic)

df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1      6   25000.0     48587.0  8.0  150.0
7302      1      7   35000.0     60000.0  9.0  220.0
7303      1     15  450000.0      3430.0  4.0  750.0
7304      1      7  139000.0     21300.0  4.0  400.0
7305      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [96]:
df

      owner  brand     price  kms_driven  age  power
0         1      1   35000.0     17654.0  3.0  110.0
1         1      2  119900.0     11000.0  4.0  350.0
2         1      3  600000.0       110.0  8.0  675.0
3         1      1   65000.0     16329.0  4.0  180.0
4         1      4   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
7301      1      6   25000.0     48587.0  8.0  150.0
7302      1      7   35000.0     60000.0  9.0  220.0
7303      1     15  450000.0      3430.0  4.0  750.0
7304      1      7  139000.0     21300.0  4.0  400.0
7305      1      7   80000.0      7127.0  5.0  220.0

[7306 rows x 6 columns]

In [99]:
y = df[["price"]]

In [100]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7301   25000.0
7302   35000.0
7303  450000.0
7304  139000.0
7305   80000.0

[7306 rows x 1 columns]

In [102]:
x=df.drop('price',axis =1)

In [103]:
x

      owner  brand  kms_driven  age  power
0         1      1     17654.0  3.0  110.0
1         1      2     11000.0  4.0  350.0
2         1      3       110.0  8.0  675.0
3         1      1     16329.0  4.0  180.0
4         1      4     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
7301      1      6     48587.0  8.0  150.0
7302      1      7     60000.0  9.0  220.0
7303      1     15      3430.0  4.0  750.0
7304      1      7     21300.0  4.0  400.0
7305      1      7      7127.0  5.0  220.0

[7306 rows x 5 columns]

In [ ]:
# x = df[['brand','owner','kms_driven','age','power']]
# y = df['price']

In [104]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2,random_state=45)

In [105]:
from sklearn.ensemble import RandomForestRegressor

In [106]:
rt=RandomForestRegressor()
rt.fit(x_train,y_train)

C:\Users\asus\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [107]:
import joblib
joblib.dump(rt,"model/rt.lb")

['model/rt.lb']

In [108]:
rt = joblib.load("model/rt.lb")

In [74]:
from sklearn.datasets import load_breast_cancer, load_diabetes
import joblib
x,y = load_breast_cancer(return_X_y=True)
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2,random_state=45)
from sklearn.svm import SVC
sv = SVC()
sv.fit(x_train,y_train)
print("svc training", sv.score(x_train,y_train))
print("svc training", sv.score(x_test,y_test))
joblib.dump(sv, "sv_load.lb")

svc training 0.9164835164835164
svc training 0.9298245614035088

['sv_load.lb']

In [75]:
model= joblib.load('sv_load.lb')

In [76]:
model.predict(x_test)

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0])

In [77]:
from sklearn.svm import SVC, SVR
sv  = SVR()
sv.fit(x_train, y_train)

SVR()

In [78]:
sv.predict(x_test)

array([ 1.00531521,  0.02699691, -0.01993654,  1.05210329,  1.00144312,
        1.06433286,  1.03502689,  1.04886211,  1.00603831,  0.99714661,
        1.03617903,  0.1042916 ,  1.04489085,  0.89518046,  1.07570836,
       -0.05286903,  0.98076768,  1.02232902,  0.87842871,  1.02369803,
        0.96992248,  1.08889847,  1.02069377,  0.90697289,  0.11339616,
        1.01517042,  0.95495697,  0.83878898,  0.45100629,  0.69874444,
        0.97300637,  1.01371463,  0.78390307, -0.03230054,  1.02238473,
        1.07334977,  1.06338248,  1.05233032,  0.67300206,  0.11301155,
        0.40973943,  0.9457381 ,  0.99485468, -0.08472224,  1.08531631,
        1.07381492,  0.88395501,  0.30497854,  0.91549732,  1.08624402,
        0.9456996 ,  1.06074819,  0.2296815 ,  1.07319394,  0.97169375,
       -0.01186624,  0.99049714,  1.00427712,  0.19858975,  1.0756825 ,
        1.08667364,  0.73109234,  1.00484647,  0.93981134,  0.84046735,
        0.75077912, -0.05097049,  0.6499581 ,  0.86093516,  0.50968005,
        0.77760747, -0.02475732,  0.07623026,  1.0138654 ,  0.94723561,
       -0.07575827,  1.01359925, -0.09648515,  0.83907642,  0.9108884 ,
       -0.02392072,  0.56050785, -0.11036171,  1.01775804,  0.08137421,
        0.56017953, -0.00997949,  1.00819915,  0.07669029,  0.13396054,
        0.02490456,  0.88458891,  1.03564168,  1.10605796,  0.20091587,
       -0.0941564 ,  0.55626181,  1.03807047,  0.73193591,  0.95470375,
        0.61784281,  1.06488627, -0.04450368, -0.05790364,  0.81338129,
        0.05272368,  0.88029911,  1.01425034,  1.00732778,  1.02885723,
        1.03487281,  1.07668568,  0.4830114 , -0.02254099])

In [79]:
print("test score",sv.score(x_test,y_test))
print("train score",sv.score(x_train,y_train))

test score 0.7287760680160389
train score 0.7357781286151779

In [80]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [81]:
model.predict(x_test)

array([ 0.85882242,  0.34831552, -0.03533072,  0.98506026,  1.19920463,
        0.9698065 ,  0.78428059,  1.10210278,  1.04528322,  1.02146231,
        0.93546403,  0.27714908,  0.95958729,  0.88568102,  0.94624551,
       -0.16157215,  1.05680931,  0.83520388,  0.88621366,  0.86893412,
        1.17649701,  1.12014197,  1.11588526,  0.9392248 ,  0.3961002 ,
        1.03538968,  0.90513524,  0.95953475,  0.40349285,  0.76740963,
        0.93995779,  1.10464896,  0.87599159, -0.0088417 ,  1.0021498 ,
        0.93769548,  1.1600488 ,  0.86663201,  0.48482084,  0.24969635,
        0.09222139,  0.87101709,  0.80176272, -0.05168001,  0.7496264 ,
        1.05398512,  1.40951057, -0.11988156,  0.88679419,  0.93230335,
        0.64429649,  0.99261551,  0.01974473,  1.06223175,  0.77559165,
        0.18646067,  0.94673165,  0.91282288,  0.23243921,  1.22346486,
        1.07742163,  0.49630269,  1.04813754,  0.82776913,  0.72869566,
        0.81504875,  0.07511761,  0.85600112,  0.72051927,  0.16779373,
        0.47569361,  0.20583732, -0.11879597,  1.07138556,  0.8561028 ,
        0.08607517,  0.8170762 , -0.28231162,  0.65835815,  0.88147825,
        0.03686028,  0.36725495,  0.14154918,  1.40486995, -0.18089123,
        0.61424125,  0.20140756,  1.02721948, -0.47458382,  0.60418602,
        0.11387706,  0.93925506,  1.00086119,  1.05371028,  0.21398846,
        0.18066782,  0.27684277,  0.89471763,  0.8802652 ,  0.93826247,
        0.76212236,  1.03976277, -0.32647762,  0.12412986,  0.76880193,
       -0.08454894,  0.38097997,  0.98984396,  0.99202459,  0.86525323,
        0.89438908,  0.99693408,  0.35237928,  0.2012838 ])

In [82]:
print("test score",model.score(x_test,y_test))
print("train score",model.score(x_train,y_train))

test score 0.7395400804771077
train score 0.7776657274650057

In [83]:
pip install joblib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: joblib in C:\Users\asus\AppData\Roaming\Python\Python313\site-packages (1.5.2)
Note: you may need to restart the kernel to use updated packages.

In [84]:
import joblib

In [85]:
ln = LinearRegression()
ln.fit(x_train,y_train)

LinearRegression()

In [86]:
joblib.dump(ln,'model/LinearRegression.lb')

['model/LinearRegression.lb']

In [1]:
from sklearn.datasets import load_breast_cancer
x,y = load_breast_cancer (return_X_y=True)
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x,y)

RandomForestClassifier()

In [2]:
rfc.score(x,y)

1.0

In [3]:
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}