In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\asus\Downloads\anand college 45 days traing\pandas\project\bike price prediction\Used_Bikes.csv")

In [3]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [5]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [6]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [7]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [8]:
df[['bike_name']]

                                  bike_name
0        TVS Star City Plus Dual Tone 110cc
1               Royal Enfield Classic 350cc
2                      Triumph Daytona 675R
3                      TVS Apache RTR 180cc
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition
...                                     ...
32643                Hero Passion Pro 100cc
32644                  TVS Apache RTR 180cc
32645              Bajaj Avenger Street 220
32646             Hero Super Splendor 125cc
32647                    Bajaj Pulsar 150cc

[32648 rows x 1 columns]

In [9]:
df[['owner']]

             owner
0      First Owner
1      First Owner
2      First Owner
3      First Owner
4      First Owner
...            ...
32643  First Owner
32644  First Owner
32645  First Owner
32646  First Owner
32647  First Owner

[32648 rows x 1 columns]

In [10]:
df.age

0         3.0
1         4.0
2         8.0
3         4.0
4         3.0
         ...
32643     4.0
32644     9.0
32645     6.0
32646    16.0
32647    13.0
Name: age, Length: 32648, dtype: float64

In [11]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [12]:
df['age'].nunique()

35

In [13]:
df['brand'].nunique()

23

In [14]:
df['owner'].nunique()

4

In [15]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [16]:
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [17]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [18]:
df.duplicated().sum()

np.int64(25324)

In [19]:
df.drop_duplicates()

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [23]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [24]:
df.dropna(inplace=True)

In [25]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [26]:
df.drop('city',axis=1, inplace=True)

In [27]:
df

,bike_name,price,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,7127.0,First Owner,5.0,220.0,Bajaj

In [28]:
char  = df.select_dtypes(include='object')

C:\Users\asus\AppData\Local\Temp\ipykernel_15652\4020120086.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  char  = df.select_dtypes(include='object')

In [29]:
char

                                 bike_name        owner            brand
0       TVS Star City Plus Dual Tone 110cc  First Owner              TVS
1              Royal Enfield Classic 350cc  First Owner    Royal Enfield
2                     Triumph Daytona 675R  First Owner          Triumph
3                     TVS Apache RTR 180cc  First Owner              TVS
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition  First Owner           Yamaha
...                                    ...          ...              ...
9362             Hero Hunk Rear Disc 150cc  First Owner             Hero
9369                   Bajaj Avenger 220cc  First Owner            Bajaj
9370        Harley-Davidson Street 750 ABS  First Owner  Harley-Davidson
9371                 Bajaj Dominar 400 ABS  First Owner            Bajaj
9372              Bajaj Avenger Street 220  First Owner            Bajaj

[7324 rows x 3 columns]

In [30]:
num = df.select_dtypes(exclude='object')

In [31]:
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [32]:
num = df.select_dtypes(exclude='O')
num

         price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [33]:
char['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [34]:
owner_dic = { 'First Owner' :1 , 'Second Owner' :2 , 'Third Owner' :3, 'Fourth Owner Or More' :4} 

char['owner'] = char['owner'].map(owner_dic)

In [35]:
char

                                 bike_name  owner            brand
0       TVS Star City Plus Dual Tone 110cc      1              TVS
1              Royal Enfield Classic 350cc      1    Royal Enfield
2                     Triumph Daytona 675R      1          Triumph
3                     TVS Apache RTR 180cc      1              TVS
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition      1           Yamaha
...                                    ...    ...              ...
9362             Hero Hunk Rear Disc 150cc      1             Hero
9369                   Bajaj Avenger 220cc      1            Bajaj
9370        Harley-Davidson Street 750 ABS      1  Harley-Davidson
9371                 Bajaj Dominar 400 ABS      1            Bajaj
9372              Bajaj Avenger Street 220      1            Bajaj

[7324 rows x 3 columns]

In [36]:
char['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [37]:
brand_dic ={'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23}
char['brand'] = char['brand'].map(brand_dic)

In [38]:
char

                                 bike_name  owner  brand
0       TVS Star City Plus Dual Tone 110cc      1      1
1              Royal Enfield Classic 350cc      1      2
2                     Triumph Daytona 675R      1      3
3                     TVS Apache RTR 180cc      1      1
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition      1      4
...                                    ...    ...    ...
9362             Hero Hunk Rear Disc 150cc      1      6
9369                   Bajaj Avenger 220cc      1      7
9370        Harley-Davidson Street 750 ABS      1     15
9371                 Bajaj Dominar 400 ABS      1      7
9372              Bajaj Avenger Street 220      1      7

[7324 rows x 3 columns]

In [39]:
total_df=pd.concat([char, num], axis=1)

In [40]:
total_df

,bike_name,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,1,1,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,1,2,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,1,3,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,1,1,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,1,4,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,1,6,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,1,7,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,1,15,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,1,7,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,1,7,80000.0,7127.0,5.0,220.0

In [41]:
total_df

,bike_name,owner,brand,price,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,1,1,35000.0,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,1,2,119900.0,11000.0,4.0,350.0
2,Triumph Daytona 675R,1,3,600000.0,110.0,8.0,675.0
3,TVS Apache RTR 180cc,1,1,65000.0,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,1,4,80000.0,10000.0,3.0,150.0
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,1,6,25000.0,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,1,7,35000.0,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,1,15,450000.0,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,1,7,139000.0,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,1,7,80000.0,7127.0,5.0,220.0

In [42]:
total_df.to_csv('clean_data.csv')

In [43]:
x=total_df.drop(['price'],axis=True)

In [44]:
x

,bike_name,owner,brand,kms_driven,age,power
0,TVS Star City Plus Dual Tone 110cc,1,1,17654.0,3.0,110.0
1,Royal Enfield Classic 350cc,1,2,11000.0,4.0,350.0
2,Triumph Daytona 675R,1,3,110.0,8.0,675.0
3,TVS Apache RTR 180cc,1,1,16329.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,1,4,10000.0,3.0,150.0
...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,1,6,48587.0,8.0,150.0
9369,Bajaj Avenger 220cc,1,7,60000.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,1,15,3430.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,1,7,21300.0,4.0,400.0
9372,Bajaj Avenger Street 220,1,7,7127.0,5.0,220.0

In [45]:
import pandas as pd
import numpy as np 
df=pd.read_csv('Used_Bikes.csv')

In [46]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [47]:
tvs_df =df[df['brand']=='TVS']

In [48]:
tvs_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [49]:
tvs_first_owner_df=tvs_df[tvs_df['owner']=='First Owner']

In [50]:
tvs_first_owner_df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [51]:
tvs_first_owner_df[tvs_first_owner_df['kms_driven']<=50000]

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
32549,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32568,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32587,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32606,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS

In [52]:
df['bike_name']

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [53]:
royal_df=df[(df['brand']=='Royal Enfield')&
            (df['owner']=='First Owner')&
(df['kms_driven']<=50000)&
(df['age']<=2)&
(df['price']<=200000)]

In [54]:
royal_df

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,First Owner,2.0,500.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
157,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,First Owner,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,First Owner,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,First Owner,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7422,Royal Enfield Himalayan 410cc Sleet ABS,175000.0,Alipore,1800.0,First Owner,2.0,410.0,Royal Enfield
7559,Royal Enfield Bullet 500cc,170000.0,Delhi,8015.0,First Owner,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,First Owner,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,First Owner,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,First Owner,2.0,350.0,Royal Enfield

In [55]:
hero_data=df[(df['brand']=='Hero')&
             (df['owner']=='First Owner')&
(df['age']<=2)&
(df['kms_driven']<=2000)&
(df['price']<=70000)]

In [56]:
hero_data

,bike_name,price,city,kms_driven,owner,age,power,brand
121,Hero Splendor iSmart Plus IBS 110cc,48672.0,Ernakulam,608.0,First Owner,2.0,110.0,Hero
172,Hero Super Splendor 125cc,43778.0,Ernakulam,948.0,First Owner,2.0,125.0,Hero
787,Hero Xtreme 200R,66000.0,Faridabad,1112.0,First Owner,2.0,200.0,Hero
2654,Hero Passion Pro i3S Alloy 100cc,60000.0,Ghaziabad,1877.0,First Owner,2.0,100.0,Hero
2952,Hero Passion Pro i3S Alloy 100cc IBS,62000.0,Mumbai,1800.0,First Owner,2.0,100.0,Hero
3298,Hero Splendor Plus IBS i3S 100cc,56000.0,Delhi,1745.0,First Owner,2.0,100.0,Hero
3349,Hero Passion Pro i3S Alloy 100cc IBS,62000.0,Mumbai,1800.0,First Owner,2.0,100.0,Hero
3583,Hero Passion Pro i3S Alloy 100cc,60000.0,Ghaziabad,1877.0,First Owner,2.0,100.0,Hero
6981,Hero Passion Pro 110cc Drum,56000.0,Delhi,1168.0,First Owner,2.0,110.0,Hero